### ISSUE TITLE
Error in `_build_gym.py` when using `--do_train`

### ISSUE THREAD

**Issue by JunShern** [facebookresearch/MetaICL#4]
Hi, I faced an error when running
```bash
python _build_gym.py --build --n_proc=40 --do_train # skip if you won't run training yourself
```
as described in the README. The error is:
```python
Traceback (most recent call last):
  File "onestop_english.py", line 62, in <module>
    main()
  File "onestop_english.py", line 59, in main
    train, dev, test = dataset.generate_k_shot_data(k=16, seed=seed, path="../data/")
  File "/home/jc11431/git/MetaICL/preprocess/fewshot_gym_dataset.py", line 171, in generate_k_shot_data
    self.save(path, k, seed, k_shot_train, k_shot_dev, k_shot_test)
  File "/home/jc11431/git/MetaICL/preprocess/fewshot_gym_dataset.py", line 109, in save
    self.write(k_shot_test, prefix + "_test.jsonl")
  File "/home/jc11431/git/MetaICL/preprocess/fewshot_gym_dataset.py", line 115, in write
    fout.write(line+"\n")
TypeError: can only concatenate tuple (not "str") to tuple
```
and this error is repeated for a large number of the tasks.

Basically, in `fewshot_gym_dataset.py` it seems like `--do_train` does not completely skip writing the test data, but it does skip the processing step so the writer fails in some cases when it tries to write the `k_shot_test` which has not been processed to a string. 

I was able to fix this by changing
```python
                self.write(k_shot_train, prefix + "_train.jsonl")
                self.write(k_shot_dev, prefix + "_dev.jsonl")
                self.write(k_shot_test, prefix + "_test.jsonl")
```
to
```python
                self.write(k_shot_train, prefix + "_train.jsonl")
                if do_test:
                    self.write(k_shot_dev, prefix + "_dev.jsonl")
                    self.write(k_shot_test, prefix + "_test.jsonl")
```

but I'm not sure if that's your intended behavior. (My intuitive understanding of `--do_test` should also skip anything to do with train examples, and vice versa)

**Comment by shmsw25** [comment]
Hi @JunShern, thank you for reporting the bug, yes you are right that it should have checked `do_test` before saving the dev and the test data. It is fixed now.
