### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by monajati** [facebookresearch/MetaICL#6]
Hi there,

After doing all installation, data downloading, and preprocessing, I ran the first line of training step:
python train.py \
  --task $task --k 16384 --test_k 16 --seed 100 --use_demonstrations --method channel \
  --do_tensorize --n_gpu 8 --n_process 40

and it gives me the following error. would you help me on this?

Traceback (most recent call last):
  File "train.py", line 140, in <module>
    main(logger, args)
  File "train.py", line 60, in main
    metaicl_data.tensorize_for_training(train_data, keyword=args.task, seed=args.seed)
  File "/home/monajati/main/fewshot_vl/MetaICL/metaicl/data.py", line 410, in tensorize_for_training
    for out in p.imap_unordered(self._tensorize_for_training, sharded_inputs):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 210, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

**Comment by shmsw25** [comment]
Hi, thanks for the question. It looks like this error is due to incompatible python versions (this code is tested with python3.8 as README says, while it seems like you are using python 3.6). You can either (1) try the solution in https://stackoverflow.com/questions/44144584/typeerror-cant-pickle-thread-lock-objects, or (2) more simply, just specify `--n_process 1` so that you won't use multipreprocessing although it could take much longer time to run preprocessing.
